<?php

/**
 * Implementation of hook_menu().
 */
function kprojectreports_menu() {
  $items['admin/settings/kprojectreports'] = array(
    'title' => 'Kproject Reports Settings',
    'page callback' => 'kprojectreports_admin_listreports',
    'access arguments' => array('manage projects'),
    'file' => 'kprojectreports_admin.inc.php',
  );

  $items['admin/settings/kprojectreports/%'] = array(
    'title' => 'Kproject Reports: Edit report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kprojectreports_admin_editreport', 3),
    'access arguments' => array('manage projects'),
    'file' => 'kprojectreports_admin.inc.php',
  );

  $items['admin/settings/kprojectreports/add'] = array(
    'title' => 'Kproject Reports: New report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kprojectreports_admin_editreport', 'add'),
    'access arguments' => array('manage projects'),
    'file' => 'kprojectreports_admin.inc.php',
  );

  $items['admin/settings/kprojectreports/%kprojectreport/delete'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kprojectreports_delete_form', 3),
    'access arguments' => array('manage projects'),
    'file' => 'kprojectreports_admin.inc.php',
  );

  return $items;
}

function kprojectreport_load($krid) {
  $result = db_query('SELECT * FROM {kprojectreports_schedules} WHERE krid=%d', $krid);
  return db_fetch_object($result);
}

function kprojectreports_cron() {
  include_once(drupal_get_path('module', 'kprojectreports') .'/kprojectreports_frequency.inc.php');

  $timetorun = FALSE;
  $date_start = 0;
  $date_end = 0;

  $result = db_query("SELECT * FROM {kprojectreports_schedules}");

  while ($report = db_fetch_object($result)) {
    // Warning: no doubt the worst method ever. Too tired, I don't care.
    // The mktime() stuff works with edge case (new year, new month) because:
    // echo mktime(23,59,59, 1, 1 - 1, 2009); = 1230785999
    // date -d @1230785999 = Wed Dec 31 23:59:59 EST 2008
    $f = 'kprojectreports_frequency_timetorun_' . $report->frequency;

    if (function_exists($f)) {
      list($timetorun, $date_start, $date_end) = $f($report);
    }

    if ($timetorun && $date_start && $date_end && $report->mail) {
      $reportfunc = $report->report; // ex: kprojectreports_timespent
      include_once(drupal_get_path('module', 'kprojectreports') .'/' . $report->report . '.inc.php');
      $report->options = unserialize($report->options);
      $output =  $reportfunc($date_start, $date_end, $report);

      $mails = explode(',', $report->mail);

      foreach ($mails as $mail) {
        // TODO: use mimemail? (attach html, csv..)
        // or c.f. http://api.drupal.org/api/function/drupal_mail/6
        $header = array(
          'Return-Path' => '<' . $emailfrom . '>',
          'Date' => date('r'),
          'From' => $emailfrom,
          'X-Mailer' => 'koumbit-kprojectreports',
          'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
          'Mime-Version' => "1.0",
        );

        $subject = $report->title;

        if (function_exists('token_replace')) {
          $subject = token_replace($report->title, 'global');
        }

        // Add introduction, if any
        if ($report->intro) {
          $output = '<p>' . $report->intro . '</p>';
        }

        // Add a footer to inform about the origin
        $output .= '<p>' . 'This is an automated report sent from ' . $servername . '. For more information, contact: ' . $emailfrom . '</p>';
  
        $message = array(
          'to' => $mail,
          'subject' => $subject,
          'body' => $output,
          'headers' => $header,
        );
  
        drupal_mail_send($message);
      }

      db_query("UPDATE {kprojectreports_schedules} SET lastrun = UNIX_TIMESTAMP() WHERE krid = %d", $report->krid);
    }
  }
}

function kprojectreports_unixdatefromarray($a) {
  return mktime(0, 0, 0, $a['month'], $a['day'], $a['year']);
}
